### PR TITLE
Enable/disable initial focus via properties

### PR DESCRIPTION
**Pull request by acspike**
proposing a property to implement @ajw625's request in #1958 for a way to disable initial focus entirely

### CODE REVIEW

**Comment by acspike** [comment]
Certainly could, and I would be happy to make that change. I added the additional "enable" because I thought I had run across someone suggesting another property where a particular control could be focused, (i.e. oxf.fr.detail.initial-focus.control.*.* ). Don't have a link to back it up though.

**Comment by ebruchez** [comment]
No strong feelings on the naming, but I wonder if there is a real use case for setting the initial focus on another control.

I notice that most boolean properties don't have a suffix, although there are a couple of exceptions (`active`, and `enable`). Naming is hard!

**Comment by acspike** [comment]
I defer. Disabling initial-focus has already been useful to us and I think it will work just as well with a shorter name. :-) At the moment, I can't dream up a situation where I would want to focus a control other than the first. Please choose what fits best with your vision for the product and let me know if you would like me to change anything in the branch.

**Comment by ebruchez** [comment]
In that case, let's use the shorter name!

**Comment by ebruchez** [comment]
Cherry-picked, closing. Thanks!

**Comment by ebruchez** [comment]
[Documented](https://github.com/orbeon/orbeon-forms/wiki/Form-Runner-~-Configuration-properties#initial-keyboard-focus)

**Comment by ebruchez** [comment]
[Moved doc](http://doc.orbeon.com/configuration/properties/form-runner.html#initial-keyboard-focus)

**Pull request closed without merging**
