### PR TITLE
Add file extension to Content-Disposition header for dynamic PDF resources

### LINKED ISSUE #2101: Dynamic PDF resource filenames lack extension
[As discussed on Twitter](https://twitter.com/acspike/status/569877965493956608)

This causes problems on Windows when accessing the pdf-url from the send action because Windows uses the extension as the primary means of determining file types. [A comment in the source code](https://github.com/orbeon/orbeon-forms/blob/master/src/main/scala/org/orbeon/oxf/xforms/processor/XFormsResourceServer.scala#L84) indicates adding extensions as a TODO list item.

### PR DESCRIPTION
**Pull request by acspike**
Fixes #2101

### CODE REVIEW

**Comment by acspike** [comment]
I realize that the code in [XFormsResourceServer.scala](https://github.com/martinluther/orbeon-forms/blob/621cccb329cb729c00396e03e0cf0cc3572a0387/src/main/scala/org/orbeon/oxf/xforms/processor/XFormsResourceServer.scala) is more general (i.e. it can return arbitrary binary resources) but would it make sense to use the same formula for the special case of the generated PDF of form data?

**Comment by ebruchez** [comment]
@acspike Which case is that? The PDF button generates a URL with a `.pdf` extension already, so I guess you mean something else?

**Comment by ebruchez** [comment]
@acspike Ah, maybe you mean getting the PDF from the Summary page?

**Comment by ebruchez** [comment]
For the original change, I was thinking that we should produce the extension based on the content-type instead of special-casing this for PDF.

So I started making some changes locally to [`Mediatypes.scala`](https://github.com/orbeon/orbeon-forms/blob/master/src/main/scala/org/orbeon/oxf/util/Mediatypes.scala) do this.

**Comment by acspike** [comment]
@ebruchez sorry for not being clear, my knowledge of orbeon is still rather weak and I have difficulty finding the correct words because of this. I'm referring to [send(content="pdf-url")](https://github.com/orbeon/orbeon-forms/wiki/Form-Runner-~-Buttons-and-Processes#send).

**Comment by ebruchez** [comment]
Done, and as mentioned above I made changes to `Mediatypes.scala` to avoid hardcoding the PDF mediatype and make it a bit more general.

**Pull request closed without merging**
