### PR TITLE
Fix 'File name too long' error when building on ecryptfs filesystem

### PR DESCRIPTION
**Pull request by artbristol**

### CODE REVIEW

**Comment by ebruchez** [comment]
I cannot find any doc on `max-classfile-name`. Are there any drawbacks? Is it safe to use it in general? Can it lead to unexpected clashes, for example?

**Comment by artbristol** [comment]
It seems to be the recommended solution to this problem...

It's defined here 

https://github.com/scala/scala/blob/c924a6452a39f03c39dfca51dca70764745e19cb/src/compiler/scala/tools/nsc/settings/ScalaSettings.scala#L114

and used in the compactify function here

https://github.com/scala/scala/blob/841389bc6f879031a8d36a5ffcca5e3c0e1fdcef/src/reflect/scala/reflect/internal/StdNames.scala#L44

It looks safe to me (it seems to rely on the start and end of the class name not colliding, i.e. dropping the middle of name)

**Comment by ebruchez** [comment]
I asked [a question](https://groups.google.com/forum/#!topic/scala-internals/hNWuwWBJCOg) on the scala-internals mailing-list.

**Comment by ebruchez** [comment]
I got a [answer to my question](https://groups.google.com/forum/#!topic/scala-internals/hNWuwWBJCOg), which doesn't seem to be very encouraging as far as making this option a default in build.xml.

I would suggest maybe instead just keep a local patch, or modify build.xml so that Scala compilation options can be passed to ant, so that this wouldn't affect our default build.

**Comment by ebruchez** [comment]
So closing this for now. Thanks for suggesting it in any case!

**Pull request closed without merging**
