### PR TITLE
allow role delimiter to be configured

### PR DESCRIPTION
**Pull request by acspike**
Address #2059

### CODE REVIEW

**Comment by ebruchez** [comment]
We this should also be used for the header-based method. Right now this is split with `(\s*[,\|]\s*)+`. In short:

- in the header case, we require at least a comma or a pipe, with optional whitespace
- in the container case, we support splitting on comma or pipe or space, without optional whitespace

I *think* we could do the same in both cases and have a single property to configure the split.

**Comment by acspike** [comment]
Recalling our [discussion on twitter](https://twitter.com/orbeon/status/555140511749517312), this regex value is not suitable as a delimiter for concatenating the values together again. If this is simply `roles-delimiter`, what would might you call that other value when it is added later?

**Comment by ebruchez** [comment]
Ah, good point. Maybe:

- `oxf.fr.authentication.roles.split`
- `oxf.fr.authentication.roles.join`

Or:

- `oxf.fr.authentication.roles-split`
- `oxf.fr.authentication.roles-join`

These are verbs, but we do have verbs in some properties.

**Comment by acspike** [comment]
Much more succinct. I have updated the branch.

**Comment by ebruchez** [comment]
I just noticed something annoying.

Our [examples for the container method](https://github.com/orbeon/orbeon-forms/wiki/Form-Runner-~-Access-Control-~-Setup#container-driven-method) show space-separated role like `form-builder-hr form-builder-finance`.

But for the header method, we show an example where roles contain spaces, like `Administrator, Power User, User`.

So with a plain regex, we would break one or the other of the examples in the doc. To be properly compatible, we would need two different regexes. We we might need to have, after all:

- `oxf.fr.authentication.header.roles.split`
- `oxf.fr.authentication.container.roles.split`

**Comment by acspike** [comment]
Being properly compatible is good. I have updated the branch.

**Comment by ebruchez** [comment]
Thanks, the change is now in as d52313a327c6ec09e2e62de5769fdc927a74dabf.

**Comment by ebruchez** [comment]
I also added defaults to the XML file. Not great to have defaults in two places but that's how it's done all over the place fd11e5f1f414657e523f68038694d6b16974aaad.

**Pull request closed without merging**
